<a href="https://colab.research.google.com/github/AdaTuanaDonmez/AdaTuanaDonmez/blob/main/Build_Video_Recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#BUILD A DATASET

import numpy

#100 inputs, 5 feature each
#each input: viewer, each feature: channel

X = numpy.zeros((100, 5),
            dtype = 'bool')

features = [ "Investing101",
            "FunnyCatVideos",
             "BuraTech",
             "MammothInteractive",
             "VideoGameReviewer" ]




for viewer in range(X.shape[0]):

  if numpy.random.random() < 0.3:   #30% of the time viewever views channel "Investing101", numpy.random.random() returns a value between 0 and 1
    X[viewer][0] = 1

    if numpy.random.random() < 0.5:
      X[viewer][1] = 1

    if numpy.random.random() < 0.2:
      X[viewer][2] = 1

    if numpy.random.random() < 0.3:
      X[viewer][3] = 1

    if numpy.random.random() < 0.4:
      X[viewer][4] = 1

  else:
    if numpy.random.random() < 0.5:
      X[viewer][1] = 1

      if numpy.random.random() < 0.3:
        X[viewer][2] = 1

      if numpy.random.random() < 0.2:
        X[viewer][3] = 1

      if numpy.random.random() < 0.4:
        X[viewer][4] = 1

    else:

       if numpy.random.random() < 0.7:
        X[viewer][2] = 1

       if numpy.random.random() < 0.55:
        X[viewer][3] = 1

       if numpy.random.random() < 0.8:
        X[viewer][4] = 1

  if X[viewer].sum() == 0:
     X[viewer][4] = 1       #if they did not encounter any of the videos or did not like any of them, recommend them the last channel by default

numpy.savetxt("viewer_profiles.txt",
              X,
              fmt = "%d")

from google.colab import files

files.download("viewer_profiles.txt")    #downloading to your PC

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
X = numpy.loadtxt("viewer_profiles.txt")

print(X.shape)

(100, 5)


In [ ]:
print(X[:5])

[[1. 1. 0. 0. 0.]
 [0. 0. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [0. 0. 1. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
number_of_MammothInteractive_likes = 0

for viewer in X:

  if viewer[3] == 1:
    number_of_MammothInteractive_likes += 1

print(number_of_MammothInteractive_likes)

32


In [ ]:
rule_valid = 0
rule_invalid = 0

for viewer in X:

  if viewer[3] == 1:
    if viewer[4] == 1:
      rule_valid += 1
    else:
      rule_invalid += 1

print( "{} times the rule is valid.".format(rule_valid))
print( "{} times the rule is invalid.".format(rule_invalid))

20 times the rule is valid.
12 times the rule is invalid.


In [ ]:
support = rule_valid

confidence = rule_valid / number_of_MammothInteractive_likes

print(" Support: {0}".format(support))

print(" Confidence: {0}".format(confidence))


 Support: 20
 Confidence: 0.625


In [ ]:
print("Confidence: {0:.1f}%".format(100*confidence))

Confidence: 62.5%


In [ ]:
number_of_samples, number_of_feautures = X.shape

from collections import defaultdict

number_of_occurences = defaultdict(int)

times_rule_valid = defaultdict(int)

times_rule_invalid = defaultdict(int)

for viewer in X:

  for premise in range(number_of_feautures):

    if viewer[premise] == 0: continue

    number_of_occurences[premise] += 1

    for conclusion in range(number_of_feautures):

      if premise == conclusion :    #premise is the first channel conclusion is the second
        continue

      if viewer[conclusion] == 1:

        times_rule_valid[(premise, conclusion)] += 1

      else:

        times_rule_invalid[(premise, conclusion)] += 1

support = times_rule_valid

confidence = defaultdict(float)

for premise, conclusion in times_rule_valid.keys():

  confidence[(premise, conclusion)] = times_rule_valid[(premise, conclusion)] / number_of_occurences[premise]

for premise, conclusion in confidence:

  first_channel = features[premise]

  second_channel = features[conclusion]

  print("If a viewer like {0}, they will also like {1}".format(first_channel, second_channel))

  print("Confidence: {0:.1f}%".format(100 * confidence[(premise, conclusion)]))

  print("Support: {0}".format(support[(premise,conclusion)]))

  print()


If a viewer like Investing101, they will also like FunnyCatVideos
Confidence: 45.8%
Support: 11

If a viewer like FunnyCatVideos, they will also like Investing101
Confidence: 23.9%
Support: 11

If a viewer like BuraTech, they will also like MammothInteractive
Confidence: 43.2%
Support: 16

If a viewer like BuraTech, they will also like VideoGameReviewer
Confidence: 64.9%
Support: 24

If a viewer like MammothInteractive, they will also like BuraTech
Confidence: 50.0%
Support: 16

If a viewer like MammothInteractive, they will also like VideoGameReviewer
Confidence: 62.5%
Support: 20

If a viewer like VideoGameReviewer, they will also like BuraTech
Confidence: 41.4%
Support: 24

If a viewer like VideoGameReviewer, they will also like MammothInteractive
Confidence: 34.5%
Support: 20

If a viewer like Investing101, they will also like VideoGameReviewer
Confidence: 45.8%
Support: 11

If a viewer like VideoGameReviewer, they will also like Investing101
Confidence: 19.0%
Support: 11

If a vie

In [ ]:
from pprint import pprint

pprint(list(support.items()))

[((0, 1), 11),
 ((1, 0), 11),
 ((2, 3), 16),
 ((2, 4), 24),
 ((3, 2), 16),
 ((3, 4), 20),
 ((4, 2), 24),
 ((4, 3), 20),
 ((0, 4), 11),
 ((4, 0), 11),
 ((1, 4), 21),
 ((4, 1), 21),
 ((1, 2), 10),
 ((2, 1), 10),
 ((0, 3), 4),
 ((1, 3), 8),
 ((3, 0), 4),
 ((3, 1), 8),
 ((0, 2), 4),
 ((2, 0), 4)]


In [ ]:
from operator import itemgetter

support_sorted = sorted(support.items(),
                        key = itemgetter(1),
                        reverse = True)

def print_results(premise, conclusion, support, confidence, features):

  first_channel = features[premise]

  second_channel = features[conclusion]

  print("If a viewer like {0}, they will also like {1}".format(first_channel, second_channel))

  print("Confidence: {0:.1f}%".format(100 * confidence[(premise, conclusion)]))

  print("Support: {0}".format(support[(premise,conclusion)]))

  print()


for index in range(5):

  (premise, conclusion) = support_sorted[index][0]
  print_results(premise, conclusion, support, confidence, features)

If a viewer like BuraTech, they will also like VideoGameReviewer
Confidence: 64.9%
Support: 24

If a viewer like VideoGameReviewer, they will also like BuraTech
Confidence: 41.4%
Support: 24

If a viewer like FunnyCatVideos, they will also like VideoGameReviewer
Confidence: 45.7%
Support: 21

If a viewer like VideoGameReviewer, they will also like FunnyCatVideos
Confidence: 36.2%
Support: 21

If a viewer like MammothInteractive, they will also like VideoGameReviewer
Confidence: 62.5%
Support: 20



In [ ]:
confidence_sorted = sorted(confidence.items(),
                        key = itemgetter(1),
                        reverse = True)


for index in range(5):

  (premise, conclusion) = confidence_sorted[index][0]
  print_results(premise, conclusion, support, confidence, features)

If a viewer like BuraTech, they will also like VideoGameReviewer
Confidence: 64.9%
Support: 24

If a viewer like MammothInteractive, they will also like VideoGameReviewer
Confidence: 62.5%
Support: 20

If a viewer like MammothInteractive, they will also like BuraTech
Confidence: 50.0%
Support: 16

If a viewer like Investing101, they will also like FunnyCatVideos
Confidence: 45.8%
Support: 11

If a viewer like Investing101, they will also like VideoGameReviewer
Confidence: 45.8%
Support: 11

